// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2121_wave_cafe.Data;

namespace _2121_wave_cafe.Migrations
{
    [DbContext(typeof(_2121_wave_cafeContext))]
    [Migration("20220323072426_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_2121_wave_cafe.Models.cafe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("GiáTiền")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgàyNhập")
                        .HasColumnType("datetime2");

                    b.Property<string>("SốLượng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TênSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("cafe");
                });
#pragma warning restore 612, 618
        }
    }
}
